### ISSUE TITLE
Throws Error when Discord is not running.

### ISSUE THREAD

**Issue by ChrisNiekler** [STadas/Ankicord#13]
**General info (please complete the following information):**
 - OS: Windows 10
 - Anki version:  ⁨2.1.49 
 - Any errors?: Yes, see copy below
 - Have you restarted Anki after installing the add-on?: Yes

**Describe the bug**
The addon throws the Error below whenever Anki is started when Discord is not running. For me, this is every time, Anki starts at system start and it starts faster than Discord does. 

----------------------------------
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Ankicord - Discord Rich Presence⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1828536813\__init__.py", line 2, in <module>
    from .src import main
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1828536813\src\main.py", line 250, in <module>
    ac = Ankicord()
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1828536813\src\main.py", line 33, in __init__
    self.rpc = pp.Presence(self.cfg_disc_id if self.cfg_disc_id else self.default_disc_id)
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1828536813\src\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\1828536813\src\pypresence\baseclient.py", line 28, in __init__
    raise DiscordNotFound
1828536813.src.pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine

**Comment by STadas** [comment]
Ah, I managed to reproduce it. I'll push an update out shortly, thanks for letting me know!
