### ISSUE TITLE
Status and cards not updating

### ISSUE THREAD

**Issue by jdohn15** [STadas/Ankicord#32]
**General info (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Anki version [e.g. 23.12.1]
 - Any errors? [
 
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 116, in __del__
  File "asyncio.proactor_events", line 108, in close
  File "asyncio.base_events", line 751, in call_soon
  File "asyncio.base_events", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 115, in __del__
  File "asyncio.proactor_events", line 79, in __repr__
  File "asyncio.windows_utils", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 115, in __del__
  File "asyncio.proactor_events", line 79, in __repr__
  File "asyncio.windows_utils", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 115, in __del__
  File "asyncio.proactor_events", line 79, in __repr__
  File "asyncio.windows_utils", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 115, in __del__
  File "asyncio.proactor_events", line 79, in __repr__
  File "asyncio.windows_utils", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020B47322700>
Traceback (most recent call last):
  File "asyncio.proactor_events", line 115, in __del__
  File "asyncio.proactor_events", line 79, in __repr__
  File "asyncio.windows_utils", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Ankicord - Discord Rich Presence ['1828536813', 2023-08-16T10:53, 'None', '']

===IDs of active AnkiWeb add-ons===
1828536813

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

]
 - Have you restarted Anki after installing the add-on? [Yes]

Discord wont update the cards left or the status. It just says I'm slacking off and wont change the number of cards i have left even if I'm in a deck and doing cards. If I open browse cards while in a deck I get this error to pop up and it updates my status to browsing cards. but then when I close it, it goes back to slacking off.

**Comment by jdohn15** [comment]
Anki 23.12.1 (1a1d4d54) (ao) Python 3.9.15 Qt 6.6.1 PyQt 6.6.1 Platform: Windows-10-10.0.22631 Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' ===Add-ons (active)=== (add-on provided name [Add-on folder, installed at, version, is config changed]) Ankicord - Discord Rich Presence ['1828536813', 2023-08-16T10:53, 'None', ''] ===IDs of active AnkiWeb add-ons=== 1828536813 ===Add-ons (inactive)=== (add-on provided name [Add-on folder, installed at, version, is config changed]) Colorful Tags Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']




Anki 23.12.1 (1a1d4d54) (ao) Python 3.9.15 Qt 6.6.1 PyQt 6.6.1 Platform: Windows-10-10.0.22631 Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000230FC532700> Traceback (most recent call last): File "asyncio.proactor_events", line 115, in __del__ File "asyncio.proactor_events", line 79, in __repr__ File "asyncio.windows_utils", line 102, in fileno ValueError: I/O operation on closed pipe Exception ignored in sys.unraisablehook: <built-in function unraisablehook> AttributeError: 'ErrorHandler' object has no attribute 'flush' ===Add-ons (active)=== (add-on provided name [Add-on folder, installed at, version, is config changed]) Ankicord - Discord Rich Presence ['1828536813', 2023-08-16T10:53, 'None', ''] ===IDs of active AnkiWeb add-ons=== 1828536813 ===Add-ons (inactive)=== (add-on provided name [Add-on folder, installed at, version, is config changed]) Colorful Tags Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']



issue with Colorful Tags (+ Hierarchical Tags), deleting the addon fixed the status changes
